# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ronin on Rails"
description: > # this means to ignore newlines until "email:"
   Give a man a fish and he’ll eat for a day.<br />
   Give a fish a man and he’ll eat for weeks.

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/wordificator.png"
# blog cover
cover: "/assets/images/london-st-james.jpg"
# cover: "/assets/images/niseko_snow_trees.jpg"

name: 'David Salgado'
author: 'David Salgado'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://digitalronin.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@digitalronin'

#fill in disqus shortname to use disqus
disqus: digitalroningithub.com

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/digitalronin
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/digitalronin
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
